{% set name = "pyee" %}
{% set version = "13.0.1" %}
{% set deselect_test = " --deselect=tests/test_trio.py::test_sync_error" %}

# E       fixture 'event_loop' not found
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jfhbrook/pyee/archive/v{{ version }}.tar.gz
  sha256: cb04405c0d77189031f79058d8c21ebfe653aefc9356e3bcb029c9b84a6d4eb5

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - setuptools-scm
  run:
    - python
    - typing_extensions

test:
  source_files:
    - tests
  imports:
    - pyee
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ deselect_test }}
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-trio
    - twisted

about:
  home: https://github.com/jfhbrook/pyee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A port of node.js's EventEmitter to python.
  description: |
    pyee supplies a EventEmitter object that is similar to the EventEmitter
    class from Node.js. It also supplies a number of subclasses with added
    support for async and threaded programming in python, such as async/await
    as seen in python 3.5+.
  doc_url: https://pyee.readthedocs.io
  dev_url: https://github.com/jfhbrook/pyee

extra:
  recipe-maintainers:
    - mxschmitt
    - kiwi0fruit
