{% set name = "pyee" %}
{% set version = "13.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jfhbrook/pyee/archive/v{{ version }}.tar.gz
  sha256: 0d09a47412dc50f52647a30499ec50e1c1248ca2d4d8d842fd3604fa76f083ad

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - setuptools-scm
  run:
    - python
    - typing_extensions

test:
  source_files:
    - tests
  imports:
    - pyee
  commands:
    - pip check
    - python run_test.py
    # pytest-trio is not avaliable on py313
    # twisted is not avaliable on windows
    - pytest -v tests  # [py<313 and not (win and x86_64)]
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-trio  # [py<313]
    - twisted  # [not win]

about:
  home: https://github.com/jfhbrook/pyee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A port of node.js's EventEmitter to python.
  description: |
    pyee supplies a EventEmitter object that is similar to the EventEmitter
    class from Node.js. It also supplies a number of subclasses with added
    support for async and threaded programming in python, such as async/await
    as seen in python 3.5+.
  doc_url: https://pyee.readthedocs.io/
  dev_url: https://github.com/jfhbrook/pyee

extra:
  recipe-maintainers:
    - mxschmitt
    - kiwi0fruit
