travis:
  secure:
    BINSTAR_TOKEN: IaMailiaStM/HZuyRV3Ffxit4wgSS+zOB3e+TXnI2SA6v0VpJvsc/SOOBXNXOM+KBvSb/qceuYADDJtNsiECov8oJSLPh2GYvy6zXwo0Hy+/hzCXDFyz4NAag0RHuR56exNvB5tqEoB0nuOnaofJyDeRzyEPyDDG6GPOMeM/Jy9sTbKYSohJucE43RVTEjlOoesX+RTbnzqt/x0mMQ5kvwPvVlNvMRKf342gMeTGk9x3BjFHc5MvAKJCuiRHwwvyPbS4oEQ622rpK2lXKvzHtyQtvIXXrR0IrQP1iFDOuitq58xtw73r8AOoyST2Lum/0dEDf6suxA2aplnx+za+pw84xEPEBDHoYA0gis4FcXc5+NvX+TB6/t3ouSntENmYfrJ3xt9LKyLwE5uHAFdrjZq9NA4BQBzUOcD2kW62DCsdpngpeYo8ye4O11XY3Y/Z4oBShx5b/OTnqtuGmFGx/AzJj7BSVbGeUCC2W9msutCOotRsTFNvSayx9FhEkOK873M83gp5wCu1/JMcyb9B7eBvs4/J2kImDRlmp0qM2rvOb3NijOlPJPYGuuIdzhtgeGV+S9yZ7lKIrso+hEL9o1OBcFVKy89to9vmT7sPmVM4l0O09cScDhMRlkii83G4VSIKF8PZN5YDa8NNRRpTjQ7QrGAYNC+5EdX1snKU/sQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
