travis:
  secure:
    BINSTAR_TOKEN: pgWgp8rikz2hwELj4jfbcf1+H0QA0rpSgv3iBmivvYEm1Xnke8Fz8mwxrQyhgRQumz2cIEIjL1mrLq2355v/Tpk5k4tV0YQmLLnQFj3Psrx9vRtbRLECI5hZwCVL6/jwOTFJA+VgKOul+bfmSWeRW9u1wv9/vYVg0Er5A35y3x+1IS6rZ+BnzzmAimeuK9bENLFjmIRkzqZVn/tXy6iBb9/nng/eqEsFqZAryO4sEbwjVlK5Os312YOLBCSLqDHNDpFh/xfkrjaXkPLEMHu1xT2+oCxZLgNpCDtSFRjMv8VzHENZQA2WEOh0UjbCUE/wpvRPoWP132FKSCJctLxVEmotAbrjG9BhO8LnV1cZCtbUT5WhokOuKk9rsaQyjICM7WHY+A8KtZrRkarHv+9oogyn2MIDLyi7sAldkJxBhvBe5lfkj0si6FKvyol7KMzvxFV0CY0pFBW9is96hNCDFRjhmr2qhU4XntlVLPzHiA/sDspRXBgGB9GspjWBld+llidit+voZq58mFtVUze6et9LZ22mpo7rD8drMG6ICP0QwkwtzrGcN0O0VENQbNfDsJR5xZ/dxTkvbS1sa/8MHH/8zvc9b5yLD1dE3PYXh6uIXQl3FrX6ZAVrf8cTB6ow/hACqouOr0pUpkCr7tVaDea0aSlpKfAeMI3zRb1cwg8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
